"""create initial tables

Revision ID: d9e81a25dee3
Revises: 
Create Date: 2026-07-01 18:07:21.418769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e81a25dee3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('domain_name', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('environment', sa.Enum('DEV', 'STAGING', 'PROD', name='environment'), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('http_port', sa.Integer(), nullable=True),
    sa.Column('https_port', sa.Integer(), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'CRITICAL', name='alertseverity'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('dns_check_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_check_results_checked_at'), 'dns_check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_dns_check_results_device_id'), 'dns_check_results', ['device_id'], unique=False)
    op.create_table('http_check_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_check_results_checked_at'), 'http_check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_http_check_results_device_id'), 'http_check_results', ['device_id'], unique=False)
    op.create_table('ping_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('is_reachable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_pct', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ping_results_checked_at'), 'ping_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_ping_results_device_id'), 'ping_results', ['device_id'], unique=False)
    op.create_table('port_check_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_check_results_checked_at'), 'port_check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_port_check_results_device_id'), 'port_check_results', ['device_id'], unique=False)
    op.create_table('ssh_metric_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('uptime', sa.String(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('load_average', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssh_metric_results_checked_at'), 'ssh_metric_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_ssh_metric_results_device_id'), 'ssh_metric_results', ['device_id'], unique=False)
    op.create_table('ssl_check_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssl_check_results_checked_at'), 'ssl_check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_ssl_check_results_device_id'), 'ssl_check_results', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssl_check_results_device_id'), table_name='ssl_check_results')
    op.drop_index(op.f('ix_ssl_check_results_checked_at'), table_name='ssl_check_results')
    op.drop_table('ssl_check_results')
    op.drop_index(op.f('ix_ssh_metric_results_device_id'), table_name='ssh_metric_results')
    op.drop_index(op.f('ix_ssh_metric_results_checked_at'), table_name='ssh_metric_results')
    op.drop_table('ssh_metric_results')
    op.drop_index(op.f('ix_port_check_results_device_id'), table_name='port_check_results')
    op.drop_index(op.f('ix_port_check_results_checked_at'), table_name='port_check_results')
    op.drop_table('port_check_results')
    op.drop_index(op.f('ix_ping_results_device_id'), table_name='ping_results')
    op.drop_index(op.f('ix_ping_results_checked_at'), table_name='ping_results')
    op.drop_table('ping_results')
    op.drop_index(op.f('ix_http_check_results_device_id'), table_name='http_check_results')
    op.drop_index(op.f('ix_http_check_results_checked_at'), table_name='http_check_results')
    op.drop_table('http_check_results')
    op.drop_index(op.f('ix_dns_check_results_device_id'), table_name='dns_check_results')
    op.drop_index(op.f('ix_dns_check_results_checked_at'), table_name='dns_check_results')
    op.drop_table('dns_check_results')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
