"""initial tables

Revision ID: f6526abf09ba
Revises: 
Create Date: 2026-07-02 12:45:15.902592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6526abf09ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'critical', name='alertseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='alertstatus'), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_hostname'), 'alerts', ['hostname'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('domain_name', sa.String(length=150), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.Enum('dev', 'staging', 'prod', name='environment'), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('http_port', sa.Integer(), nullable=True),
    sa.Column('https_port', sa.Integer(), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=True),
    sa.Column('record_type', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_device_id'), 'dns_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_dns_records_domain'), 'dns_records', ['domain'], unique=False)
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    op.create_table('http_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_checks_device_id'), 'http_checks', ['device_id'], unique=False)
    op.create_index(op.f('ix_http_checks_id'), 'http_checks', ['id'], unique=False)
    op.create_table('ping_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_pct', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ping_results_device_id'), 'ping_results', ['device_id'], unique=False)
    op.create_index(op.f('ix_ping_results_hostname'), 'ping_results', ['hostname'], unique=False)
    op.create_index(op.f('ix_ping_results_id'), 'ping_results', ['id'], unique=False)
    op.create_table('port_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_checks_device_id'), 'port_checks', ['device_id'], unique=False)
    op.create_index(op.f('ix_port_checks_hostname'), 'port_checks', ['hostname'], unique=False)
    op.create_index(op.f('ix_port_checks_id'), 'port_checks', ['id'], unique=False)
    op.create_table('ssh_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('uptime', sa.String(length=100), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('load_average', sa.String(length=50), nullable=True),
    sa.Column('logged_in_users', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssh_metrics_device_id'), 'ssh_metrics', ['device_id'], unique=False)
    op.create_index(op.f('ix_ssh_metrics_id'), 'ssh_metrics', ['id'], unique=False)
    op.create_table('ssl_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssl_checks_device_id'), 'ssl_checks', ['device_id'], unique=False)
    op.create_index(op.f('ix_ssl_checks_domain'), 'ssl_checks', ['domain'], unique=False)
    op.create_index(op.f('ix_ssl_checks_id'), 'ssl_checks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ssl_checks_id'), table_name='ssl_checks')
    op.drop_index(op.f('ix_ssl_checks_domain'), table_name='ssl_checks')
    op.drop_index(op.f('ix_ssl_checks_device_id'), table_name='ssl_checks')
    op.drop_table('ssl_checks')
    op.drop_index(op.f('ix_ssh_metrics_id'), table_name='ssh_metrics')
    op.drop_index(op.f('ix_ssh_metrics_device_id'), table_name='ssh_metrics')
    op.drop_table('ssh_metrics')
    op.drop_index(op.f('ix_port_checks_id'), table_name='port_checks')
    op.drop_index(op.f('ix_port_checks_hostname'), table_name='port_checks')
    op.drop_index(op.f('ix_port_checks_device_id'), table_name='port_checks')
    op.drop_table('port_checks')
    op.drop_index(op.f('ix_ping_results_id'), table_name='ping_results')
    op.drop_index(op.f('ix_ping_results_hostname'), table_name='ping_results')
    op.drop_index(op.f('ix_ping_results_device_id'), table_name='ping_results')
    op.drop_table('ping_results')
    op.drop_index(op.f('ix_http_checks_id'), table_name='http_checks')
    op.drop_index(op.f('ix_http_checks_device_id'), table_name='http_checks')
    op.drop_table('http_checks')
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_domain'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_device_id'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_hostname'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
